spring:
  application:
    name: transfer
    gateway:
      host: ${GATEWAY_HOST:http://account:8080}
    kafka:
      topics:
        topic: ${KAFKA_TOPIC:transfer-notifications}

  r2dbc:
    url: r2dbc:postgresql://${DB_TRANSFER_HOST:localhost}:${DB_TRANSFER_PORT:5432}/${DB_TRANSFER_NAME:transfer_db}
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

  datasource:
    url: jdbc:postgresql://${DB_TRANSFER_HOST:localhost}:${DB_TRANSFER_PORT:5432}/${DB_TRANSFER_NAME:transfer_db}
    username: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/transfer/db.changelog-master.yaml
    default-schema: ${DB_SCHEMA:public}
    url: jdbc:postgresql://${DB_TRANSFER_HOST:localhost}:${DB_TRANSFER_PORT:5432}/${DB_TRANSFER_NAME:transfer_db}
    user: ${DB_USER_NAME:bank_admin}
    password: ${DB_PASSWORD:bank_password}
    contexts: dev,test,default

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak/realms/bank/protocol/openid-connect/certs
          issuer-uri: http://keycloak/realms/bank
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${spring.application.name}
            client-secret: ${KEYCLOAK_TRANSFER_SECRET:c4999939-58e8-64de-a84f-2814909941ae}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak/realms/bank

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus,metrics
      base-path: /actuator
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      access: unrestricted
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1