spring:
  application:
    name: front-ui
  gateway:
    host: ${GATEWAY_HOST:http://gateway:8080}

  config:
    import:
      - "optional:classpath:application.yml"

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: front-ui
            client-secret: ${KEYCLOAK_FRONT_UI_SECRET:90bd600c-7781-4435-961e-1f5139265f7c}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://keycloak/realms/bank

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus,metrics
      base-path: /actuator
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      access: unrestricted
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1