apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-theme
data:
  login.ftl: |-
{{ .Files.Get "files/login.ftl" | indent 4 }}
  register.ftl: |-
{{ .Files.Get "files/register.ftl" | indent 4 }}
  style.css: |-
{{ .Files.Get "templates/files/style.css" | indent 4 }}
  theme.properties: |-
{{ .Files.Get "files/theme.properties" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-import
data:
  realm.json: |-
{{ .Files.Get "files/realm-export.json" | indent 4 }}