server:
  port: 0

spring:
  main:
    allow-bean-definition-overriding: true

resilience4j:
  circuitbreaker:
    instances:
      gateway-cb:
        slidingWindowSize: 5
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 1s